server:
  port: 8080
  servlet:
    # Context Path must be specified.
    # reason : the session tracking is cookie based and each session cookie must have a unique path
    context-path: /client

security:
  basic:
    enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: H2
    show-sql: TRUE
    hibernate:
      ddl-auto: 'create'

# REDIS를 Session 저장용으로 사용하는 경우 사용,
#  session:
#    store-type: redis

#  redis: # 해당 서버에 redis데몬이 6379포트로 떠있어야 함
#    host: 127.0.0.1
#    port: 6379